'use strict';

module.exports = function(grunt) {

	// load all grunt tasks
	require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

	grunt.initConfig({
		config: grunt.file.readJSON('config.json'),
		compass: {
			options: {
				cssDir: '<%= config.buildPath %>/css',
				sassDir: 'sass'
			},
			dev: {
				options: {
					outputStyle: 'expanded',
					debugInfo: true
				}
			},
			prod: {
				options: {
					outputStyle: 'compressed'
				}
			}
		},
		connect: {
			dev: {
				options: {
					port: 7000,
					middleware: function(connect, options) {
						return [
							// serve files in /dist as if they were in the root.
							connect.static(__dirname + '/<%= config.buildPath %>'),
							// but serve everything else from the root
							connect.static(__dirname)
						];
					}
				}
			},
			prod: {
				options: {
					base: '<%= config.buildPath %>',
					keepalive: true,
				}
			}
		},
		copy: {
			build: {
				files: [
					{expand: true, cwd: 'contents/', src: '**/*.{jpg,png}', dest: '<%= config.buildPath %>/'}
				]
			}
		},
		'gh-pages': {
			prod: {
				options: {
					base: '<%= config.buildPath %>'
				},
				src: ['**/*']
			}
		},
		handlebars_html: {
			options : {
				partialDir : 'templates/partials',
				helperDir : 'templates/helpers'
			},
			dev: {
				src: 'templates/*.hbs',
				dest: '<%= config.buildPath %>',
				data: 'build/data.json',
			},
			prod: '<%= handlebars_html.dev %>'
		},
		import_contents: {
			options : {
				baseDir: 'contents',
				config : 'config.json',
				markdown: {
					breaks: true,
					smartLists: true,
					smartypants: true,
					langPrefix: 'language-'
				}
			},
			all: {
				src: 'contents/**/*.{json,md}',
				dest: 'build/data.json'
			}
		},
		requirejs: {
			prod: {
				options: {
					baseUrl: '.',
					mainConfigFile: 'js/config.js',
					name: 'js/app',
					out: '<%= config.buildPath %>/app.js',
					optimize: 'uglify2',
					generateSourceMaps: true,
					preserveLicenseComments: false,
				}
			}
		},
		fix_sourcemaps: {
			prod: ['<%= config.buildPath %>/app.js.map']
		},
		watch: {
			options: {
				livereload: '<%= config.livereload %>' || 35729
			},
			css: {
				files: ['sass/**/*.scss'],
				tasks: ['compass:dev']
			},
			contents: {
				files: ['contents/**/*.{json,md}'],
				tasks: ['import_contents']
			},
			templates: {
				files: ['templates/**/*.{hbs,html}'],
				tasks: ['handlebars_html:dev']
			}
		}
	});

	// load local tasks
	grunt.loadTasks('tasks');

	// copied from https://github.com/cowboy/wesbos/blob/master/Gruntfile.js
	grunt.registerMultiTask('fix_sourcemaps', 'Fix sourcemaps generated by requirejs task.', function() {
		this.filesSrc.forEach(function(mapfile) {
			var data = grunt.file.readJSON(mapfile);
			// Sources should be relative to the project root, but are actually
			// relative to where app.js lives. I'm not sure how to change this,
			// other than to rewrite ../ and ../../ (and ../ times 8 for !json??)
			data.sources = data.sources.map(function(filepath) {
				return filepath.replace(/^(\.\.\/)+/, function(parents) {
					var depth = parents.match(/\.\.\//g).length - 1;
					return ['build/', ''][depth] || '';
				});
			});
			grunt.file.write(mapfile, JSON.stringify(data));
		});
	});


	grunt.registerTask('dev', [
		'import_contents',
		'copy',
		'handlebars_html:dev',
		'compass:dev',
		'connect:dev',
		'watch'
	]);

	grunt.registerTask('build', [
		'import_contents',
		'copy',
		'handlebars_html:prod',
		'compass:prod',
		'requirejs:prod',
		'fix_sourcemaps:prod'
	]);

	grunt.registerTask('deploy', 'Deploy site via gh-pages.', [
		'build',
		'gh-pages'
	])

	grunt.registerTask('prod', [

	]);

	grunt.registerTask('default', ['dev']);
}